### ISSUE TITLE
Mention https://github.com/ott-lang/ott

### ISSUE THREAD

**Issue by Blaisorblade** [DIKU-EDU/ott#1]
Thanks for this! Just a small nit: Googling `Ott Coq` led me to both this webpage and https://github.com/ott-lang/ott, but I guess the latter is the main repo? Took me a while to guess; a link and/or a clarification would be useful.

**Comment by oleks** [comment]
I'd say downright that this repository is deprecated. The last commit here was before the first commit there. However, maybe it is worth pushing some of this stuff up-stream. Thanks for bringing this to my attention!

**Comment by Blaisorblade** [comment]
Thanks for the reply — I quickly PR’ed a possible clarification which should be sufficient to my need, in case you want a quick solution. Feel free to proceed as you prefer; please do add a link :-).

**Comment by Blaisorblade** [comment]
Thanks, closed!
